### ISSUE TITLE
Borders are transparent, when hiding titlebar

### ISSUE THREAD

**Issue by gikari** [paulmcauley/classikstyles#4]
## Steps to reproduce
1. Create the following window override:
![image](https://user-images.githubusercontent.com/14205339/126868390-79fc897a-126c-47b4-b7c4-abfb67e6a2bb.png)

2. Apply the settings

## Expected behavior
Window borders use the same color, as before.

## Actual behavior
Window borders are transparent.
![image](https://user-images.githubusercontent.com/14205339/126868443-dbb6b241-617a-420b-9fc6-14420b016b0d.png)

**Comment by paulmcauley** [comment]
Yes, this has already been fixed on the git master. The fix will be available in v 2.7.

**Comment by gikari** [comment]
Thanks, it works on master.
