### ISSUE TITLE
Semi-transparent window corner artifacts

### ISSUE THREAD

**Issue by efermi** [paulmcauley/classikstyles#6]
Distro: manjaro
Package version: 2.6.breeze5.22.80-1

With rounded corners enabled there still a visible texture remains:
![Screenshot_20210817_185533](https://user-images.githubusercontent.com/3966555/129763425-fca7fcb0-7b30-46c6-bb2c-c94b1c800b06.png)
.

**Comment by paulmcauley** [comment]
This is a well known bug with KDE Plasma and occurs when blur is enabled in Desktop Effects : https://bugs.kde.org/show_bug.cgi?id=395725

It requires a change to KDecoration and Kwin to fix, as well as the Window Decoration.

**Comment by efermi** [comment]
Sorry, I didn't know that. Is it enough to disable blur here https://github.com/paulmcauley/classikstyles/blob/a78721b5353bf7e848a052082e6fd600b3104ee4/kdecoration/breeze.json#L12 as I don't use transparency anyway?

**Comment by paulmcauley** [comment]
> Sorry, I didn't know that. Is it enough to disable blur here
> 
> https://github.com/paulmcauley/classikstyles/blob/a78721b5353bf7e848a052082e6fd600b3104ee4/kdecoration/breeze.json#L12
> as I don't use transparency anyway?

Yes, if you set blur there to false and recompile you will not have the corner blur problem. I was wavering on whether that should be true or false by default, but think it may be better to have it true and try to eventually get it fixed properly in KDE.

**Comment by efermi** [comment]
Works for me, thank you!

**Comment by paulmcauley** [comment]
You will no longer need to make this edit to breeze.json from version 2.7 (and on current master). I have updated the code with https://github.com/paulmcauley/classikstyles/commit/bcb7d7a168b04e1463e582db65cfdbbc80268616 so that blur is only used when transparency is enabled, and that there is also an explicit setting for enabling blur with transparency.

**Comment by efermi** [comment]
That's great, thank you!
