### ISSUE TITLE
Advice reviving old themes.

### ISSUE THREAD

**Issue by mathieujobin** [paulmcauley/classikstyles#7]
Hi

Can you offer any advice on how one could revive old KDE themes such as the Keramik window decoration?

Also do you think Aurora is the best we can have at producing pixmap based themes or we could make it easier?

**Comment by paulmcauley** [comment]
If you already know C++ I would just fork and not bother with Aurorae as it is just too buggy, especially on HiDPI displays (at least for now until bugs are fixed).

I am not that familiar with Keramik or how it was implemented but I see this it it?
![keramik](https://user-images.githubusercontent.com/6924479/142771952-4d1b931d-3b01-4704-aa42-0f603fda279d.jpg)
It has quite an unusual highlight of the title caption, and not something I had thought about. Not trivial to implement as it also changes the window shape, but could be done.

On making customization easier, I plan to update ClassikStyles in the future to try to have the ability to load in your system's svg system icon theme for the icons. That would be allow easier and better customisation than aurorae for the vast majority of cases, and also much easier than creating icons in QPainter!
