### ISSUE TITLE
[BUG] Window Decorations does not shown when using latte dock on wayland

### ISSUE THREAD

**Issue by MohamedIO** [paulmcauley/classikstyles#87]
Hi @paulmcauley ,

Window Decorations (close,restore,minimize) does not shown when using latte dock with global menu on wayland, it works on x11.

i hope this bug fix ASAP.

Thanks,

**Comment by paulmcauley** [comment]
What widget are you using to show window buttons? As far as I can see Latte Dock itself does not include a way to show window buttons?

Klassy works with https://github.com/chermnyx/applet-window-buttons/tree/dumb_5.27_support on Plasma 5.27 Wayland:
![applet_window_buttons](https://github.com/paulmcauley/klassy/assets/6924479/f5521049-8d7c-4096-a3cf-cea636fc8198)

**Comment by paulmcauley** [comment]
It is still not clear to me from your description what your problem is. Please could you provide a screenshot.

**Comment by paulmcauley** [comment]
Could you also provide a screenshot of what you expect things to look like with Breeze?
